import 'package:flutter/material.dart';
import 'package:flutter_cool_toolbar_challenge/models/menu_item.dart';

List<IconItem> iconList = [
  IconItem(icon: Icons.home, color: Colors.blue, label: 'Home'),
  IconItem(icon: Icons.favorite, color: Colors.red, label: 'Favorite'),
  IconItem(icon: Icons.settings, color: Colors.green, label: 'Settings'),
  IconItem(icon: Icons.ac_unit, color: Colors.lightBlue, label: 'AC Unit'),
  IconItem(icon: Icons.access_alarm, color: Colors.orange, label: 'Alarm'),
  IconItem(icon: Icons.accessibility, color: Colors.purple, label: 'Accessibility'),
  IconItem(icon: Icons.account_balance, color: Colors.amber, label: 'Account Balance'),
  IconItem(icon: Icons.add, color: Colors.teal, label: 'Add'),
  IconItem(icon: Icons.attach_file, color: Colors.brown, label: 'Attach File'),
  IconItem(icon: Icons.camera_alt, color: Colors.indigo, label: 'Camera'),
  IconItem(icon: Icons.check, color: Colors.redAccent, label: 'Check'),
  IconItem(icon: Icons.cloud, color: Colors.lightBlueAccent, label: 'Cloud'),
  IconItem(icon: Icons.code, color: Colors.pink, label: 'Code'),
  IconItem(icon: Icons.contact_mail, color: Colors.deepOrange, label: 'Contact Mail'),
  IconItem(icon: Icons.crop, color: Colors.greenAccent, label: 'Crop'),
  IconItem(icon: Icons.dashboard, color: Colors.blueGrey, label: 'Dashboard'),
  IconItem(icon: Icons.delete, color: Colors.redAccent, label: 'Delete'),
  IconItem(icon: Icons.desktop_mac, color: Colors.deepPurple, label: 'Desktop'),
  IconItem(icon: Icons.directions_bus, color: Colors.orange, label: 'Bus'),
  IconItem(icon: Icons.drive_eta, color: Colors.blue, label: 'Drive'),
  IconItem(icon: Icons.email, color: Colors.amber, label: 'Email'),
  IconItem(icon: Icons.explore, color: Colors.blueGrey, label: 'Explore'),
  IconItem(icon: Icons.favorite_border, color: Colors.pink, label: 'Favorite Border'),
  IconItem(icon: Icons.flight_takeoff, color: Colors.indigo, label: 'Flight'),
  IconItem(icon: Icons.group, color: Colors.teal, label: 'Group'),
  IconItem(icon: Icons.headset, color: Colors.deepPurple, label: 'Headset'),
  IconItem(icon: Icons.help_outline, color: Colors.blueAccent, label: 'Help'),
  IconItem(icon: Icons.insert_chart, color: Colors.orange, label: 'Chart'),
  IconItem(icon: Icons.keyboard, color: Colors.blueGrey, label: 'Keyboard'),
  IconItem(icon: Icons.lightbulb_outline, color: Colors.amber, label: 'Lightbulb'),
  IconItem(icon: Icons.local_cafe, color: Colors.brown, label: 'Cafe'),
  IconItem(icon: Icons.location_on, color: Colors.red, label: 'Location'),
  IconItem(icon: Icons.mail_outline, color: Colors.deepOrange, label: 'Mail'),
  IconItem(icon: Icons.mic, color: Colors.green, label: 'Mic'),
  IconItem(icon: Icons.movie, color: Colors.deepPurpleAccent, label: 'Movie'),
  IconItem(icon: Icons.notifications_none, color: Colors.blue, label: 'Notifications'),
  IconItem(icon: Icons.palette, color: Colors.indigo, label: 'Palette'),
  IconItem(icon: Icons.phone, color: Colors.greenAccent, label: 'Phone'),
  IconItem(icon: Icons.print, color: Colors.purple, label: 'Print'),
  IconItem(icon: Icons.public, color: Colors.blue, label: 'Public'),
  IconItem(icon: Icons.radio, color: Colors.red, label: 'Radio'),
  IconItem(icon: Icons.save, color: Colors.blue, label: 'Save'),
  IconItem(icon: Icons.security, color: Colors.green, label: 'Security'),
  IconItem(icon: Icons.star, color: Colors.amber, label: 'Star'),
  IconItem(icon: Icons.thumb_up, color: Colors.blue, label: 'Thumb Up'),
  IconItem(icon: Icons.translate, color: Colors.deepOrange, label: 'Translate'),
];
